### ISSUE TITLE
ffmpeg报错

### ISSUE THREAD

**Issue by Liu-Stephen** [KimmyXYC/BiliLive-Auto-Streaming#11]
Press [q] to stop, [?] for help
av_interleaved_write_frame(): End of file
[flv @ 029CC940] Failed to update header with correct duration.
[flv @ 029CC940] Failed to update header with correct filesize.
Error writing trailer of rtmp://live-push.bilivideo.com/live-bvc/?streamname=live_381831940_7339786&key=334d247****4464da&schedule=rtmp&pflag=1: End of file
frame= 8791 fps= 23 q=-1.0 Lsize=  317847kB time=00:06:06.25 bitrate=7109.3kbits/s speed=0.968x    
video:305055kB audio:12398kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.123921%
Conversion failed!

关键行：
[flv @ 029CC940] Failed to update header with correct duration.
[flv @ 029CC940] Failed to update header with correct filesize.

如何触发：
播放文件夹中的视频，有两个视频，两个视频时长都是 1:30:00 一个半小时；第一个视频可以正常播放完，但是推流到第二个视频的时候就抛出这个异常了。第二个视频播了一分钟左右。

可能是视频时间太长了。

在网上查了一下，说是要在 ffmpeg 推流命令中加  -flvflags no_duration_filesize ，让它不报异常。

原文链接：https://blog.csdn.net/sinat_41892387/article/details/122288215

具体的我也不太懂，作者可以去看一下。

**Comment by KimmyXYC** [comment]
你先在 https://github.com/KimmyXYC/BiliLive-Auto-Streaming/blob/c5ee55aa27ad9ce8626676f0f12b35368952270f/App/Stream.py#L50 这里自己加下参数试试，看看还会不会报错，不报错的话我进行修改

**Comment by KimmyXYC** [comment]
我没这么长的视频测试

**Comment by Liu-Stephen** [comment]
ok

**Comment by KimmyXYC** [comment]
> ok

添加参数之后，问题解决了吗

**Comment by Liu-Stephen** [comment]
可以的，忘记反馈了抱歉。
