### ISSUE TITLE
App.Live:start_live:45 - 开播失败, 错误码: 60003

### ISSUE THREAD

**Issue by FairyWorld** [KimmyXYC/BiliLive-Auto-Streaming#12]
App.Live:start_live:45 - 开播失败, 错误码: 60003

**Comment by KimmyXYC** [comment]
请在 https://github.com/KimmyXYC/BiliLive-Auto-Streaming/blob/4563300ffcba91b05c36078c15e5402b7cccbe42/main.py#L59 日志等级设置为 Debug 再获取报错
