### ISSUE TITLE
青龙面板怎么使用?

### ISSUE THREAD

**Issue by FairyWorld** [KimmyXYC/BiliLive-Auto-Streaming#4]
青龙面板怎么使用?

**Comment by KimmyXYC** [comment]
没用过青龙面板 我等下看看

**Comment by FairyWorld** [comment]
手动添加任务可以直接在青龙面板运行，不过青龙无法通过停止按钮关闭正在执行的直播，除非手动在终端终止进程

**Comment by KimmyXYC** [comment]
直播使用的是 ffmpeg 直接中途关闭，会导致 ffmpeg 未关闭 以及 停播哔哩哔哩直播的函数 未执行

**Comment by KimmyXYC** [comment]
可以优化 我等会写了试试

**Comment by KimmyXYC** [comment]
不会写 等大佬来解决这个问题

**Comment by KimmyXYC** [comment]
应该解决了 可以再试试看

**Comment by FairyWorld** [comment]
> 用过青龙面板 我等下看看



> 应该解决了 可以再试试看

青龙面板停止任务后直播间还是在直播

**Comment by KimmyXYC** [comment]
> > 用过青龙面板 我等下看看
> 
> > 应该解决了 可以再试试看
> 
> 青龙面板停止任务后直播间还是在直播

那估计是 青龙面板 发出的 停止信号 不一样了

**Comment by KimmyXYC** [comment]
如果是 直接杀进程的话 没法解决
可能需要根据 青龙面板 的方法 对它单独适配
（不是很想写，我不用青龙面板）

**Comment by KimmyXYC** [comment]
直播需要 开播和停播 才算完整
这点与普通签到脚本不同
中途强行杀死进程会使停播函数未执行
并且 ffmpeg 的进程是单独的 青龙只杀 运行的 Python 程序，而不关闭 ffmpeg

**Comment by KimmyXYC** [comment]
如果有其他脚本有解决方法 请麻烦告诉我

**Comment by FairyWorld** [comment]
> 如果有其他脚本有解决方法 请麻烦告诉我

发现了个新问题，青龙面板定时自动执行任务播放到5分钟会自动结束直播，但是手动点击开始执行任务就会正常按照配置的时长直播

**Comment by KimmyXYC** [comment]
> > 如果有其他脚本有解决方法 请麻烦告诉我
> 
> 发现了个新问题，青龙面板定时自动执行任务播放到5分钟会自动结束直播，但是手动点击开始执行任务就会正常按照配置的时长直播

不是很懂青龙面板，麻烦发下日志
