### ISSUE TITLE
video path改为文件夹路径后无法使用

### ISSUE THREAD

**Issue by RAINighty** [KimmyXYC/BiliLive-Auto-Streaming#6]
错误日志
`直播已开始
开始推流
expected str, bytes or os.PathLike object, not int
停播成功
直播完成，共耗时 6 秒`

config
`  "deploy": {
    "type": 1,
    "video_path": "E:/Auto-Streaming/video",
    "live_time": 4000`

**Comment by KimmyXYC** [comment]
我的问题 代码改错了
