### ISSUE TITLE
通知可以增加bark吗？

### ISSUE THREAD

**Issue by 2375399351** [KimmyXYC/BiliLive-Auto-Streaming#7]
最好可以自定义bark的ip和密钥，还有就是开始直播后会发送通知开始直播吗？我这边没有显示通知

**Comment by KimmyXYC** [comment]
bark 没用过，请提供请求样例

直播开始后不会推送消息，这个可以改

**Comment by 2375399351** [comment]
> bark 没用过，请提供请求样例
> 
> 
> 
> 直播开始后不会推送消息，这个可以改

![image](https://github.com/KimmyXYC/BiliLive-Auto-Streaming/assets/34334506/8a32a733-320e-4df7-9328-509a57e42c08)
我自己改了下不知道行不行，不知道这个通知是怎么触发的，还有脚本可以设置多个文件循环播放吗？

**Comment by KimmyXYC** [comment]
触发请调用 https://github.com/KimmyXYC/BiliLive-Auto-Streaming/blob/main/App/Push.py#L11 这个函数

支持多文件循环播放 配置文件中 type 设置为 1  video_path 设置为只包含要播放的视频的文件夹即可
```
"deploy": {
        "type": 0, //路径类型，0 表示单个视频文件路径（或视频直链），1表示文件夹路径
        "video_path": "video.flv", //视频文件路径（支持相对路径和绝对路径以及视频直链）
        "live_time": 2100 //目标直播时长（单位：秒）
                          //0 表示播完当前视频后停止；-1 表示 24h 持续直播
    },
```

**Comment by KimmyXYC** [comment]
开始直播通知触发等我提交一段代码

**Comment by 2375399351** [comment]
> 触发请调用 https://github.com/KimmyXYC/BiliLive-Auto-Streaming/blob/main/App/Push.py#L11 这个函数
> 
> 
> 
> 支持多文件循环播放 配置文件中 type 设置为 1  video_path 设置为只包含要播放的视频的文件夹即可
> 
> ```
> 
> "deploy": {
> 
>         "type": 0, //路径类型，0 表示单个视频文件路径（或视频直链），1表示文件夹路径
> 
>         "video_path": "video.flv", //视频文件路径（支持相对路径和绝对路径以及视频直链）
> 
>         "live_time": 2100 //目标直播时长（单位：秒）
> 
>                           //0 表示播完当前视频后停止；-1 表示 24h 持续直播
> 
>     },
> 
> ```

ok

**Comment by KimmyXYC** [comment]
试试能不能用

**Comment by 2375399351** [comment]
> 试试能不能用

这个通知怎么手动测试啊？我不知道哪个命令可以运行这个通知，config.json里面设置true了，但是我运行main.py后没有通知

**Comment by KimmyXYC** [comment]
> > 试试能不能用
> 
> 这个通知怎么手动测试啊？我不知道哪个命令可以运行这个通知，config.json里面设置true了，但是我运行main.py后没有通知

用刚刚提交的 [test.py](https://github.com/KimmyXYC/BiliLive-Auto-Streaming/blob/main/test.py)
`python3 test.py`

**Comment by 2375399351** [comment]
> > > 试试能不能用
> > 
> > 
> > 这个通知怎么手动测试啊？我不知道哪个命令可以运行这个通知，config.json里面设置true了，但是我运行main.py后没有通知
> 
> 用刚刚提交的 [test.py](https://github.com/KimmyXYC/BiliLive-Auto-Streaming/blob/main/test.py) `python3 test.py`

可以的,不过https://github.com/KimmyXYC/BiliLive-Auto-Streaming/blob/main/App/Push.py#L84 这里可以在内容全面加个/ 
让【BiliLive】变成标题

**Comment by KimmyXYC** [comment]
> > > > 试试能不能用
> > > 
> > > 
> > > 这个通知怎么手动测试啊？我不知道哪个命令可以运行这个通知，config.json里面设置true了，但是我运行main.py后没有通知
> > 
> > 
> > 用刚刚提交的 [test.py](https://github.com/KimmyXYC/BiliLive-Auto-Streaming/blob/main/test.py) `python3 test.py`
> 
> 可以的,不过https://github.com/KimmyXYC/BiliLive-Auto-Streaming/blob/main/App/Push.py#L84 这里可以在内容全面加个/ 让【BiliLive】变成标题

好了
