### ISSUE TITLE
停止 main.py 脚本，提示停播失败

### ISSUE THREAD

**Issue by Liu-Stephen** [KimmyXYC/BiliLive-Auto-Streaming#9]
2023-07-22T13:54:45.438933+0800 - SUCCESS - 检测到终止信号, 开始停播
2023-07-22T13:54:45.633019+0800 - ERROR - 停播失败, 错误码: -400

**Comment by KimmyXYC** [comment]
> 2023-07-22T13:54:45.438933+0800 - SUCCESS - 检测到终止信号, 开始停播 2023-07-22T13:54:45.633019+0800 - ERROR - 停播失败, 错误码: -400

请提供配置文件 cookies 和播放密钥部分可以打码
另外请提供是如何触发的，什么情况下触发的

**Comment by Liu-Stephen** [comment]
"cookies": "DedeUserID=*****; DedeUserID__ckMd5=b2642847bc******; SESSDATA=a6257d1f%2C1705549679%2C55b9a%2A72qau_jW86wxb06oMjr6j4B5t8drk-m9kR6yNZ5fR9qGDrMEVE_EnCk9UIxvLWqdUkJkrZ5g******; bili_jct=2beab7f0fc125d6c585c08b51a87501*; sid=farysr6*"；

是这个 cookies 吗？* 是我加的
在 PyCharm 中运行 login.py 后，直接运行 main.py 可以正常直播，config配置好了；main 跑起来之后，播了一段时间，点停止运行就出现上面的问题。点了停止之后b站直播间在转圈，过几分钟后才停止直播。

**Comment by Liu-Stephen** [comment]
难道是因为没有正确停止代码？

**Comment by KimmyXYC** [comment]
> 难道是因为没有正确停止代码？

按理触发到终止信号 会切断直播
过几分钟自动停是b站的机制，自动结束长时间无推流的用户

**Comment by KimmyXYC** [comment]
哔哩哔哩引入了新的机制鉴权，可能与这方面有关，有空我测试一下

**Comment by KimmyXYC** [comment]
麻烦更新到最新 commit 重现一下问题
然后发送控制台输出的完整 log 信息

**Comment by KimmyXYC** [comment]
哦 稍等下，我似乎知道问题所在了

**Comment by KimmyXYC** [comment]
> 难道是因为没有正确停止代码？

更新到最新 commit 再试试看 应该没有问题了

**Comment by KimmyXYC** [comment]
这个代码是我以前的练手作品，里面有些地方不合理或有错误，抽空重写一下
